version: '3.8'

services:
  mediprep-app:
    build: .
    container_name: mediprep-app
    restart: always
    ports:
      - "5001:5001"
    environment:
      KAFKA_BROKER: mediprep-eventhub.servicebus.windows.net:9093
      KAFKA_SASL_USERNAME: $ConnectionString
      KAFKA_SASL_PASSWORD: Endpoint=sb://mediprep-eventhub.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=+6y+vNeYlEdjDX6RPIDAY2bQuMnHeRk3n+AEhJXBkiA=
      KAFKA_CLIENT_ID: MEDIPREP
      KAFKA_EXAM_QUESTION_FILE_TOPIC: examquestionfile
      KAFKA_EMAIL_TOPIC: email
      # REDIS_HOST: mediprep-redis
    networks:
      - mediprep-network

  # Optional Redis (uncomment if still needed)
  # mediprep-redis:
  #   image: redis:latest
  #   container_name: mediprep-redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - mediprep-network
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

networks:
  mediprep-network:
    driver: bridge
